version: '3'
services:

  voicechat-lvlup-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TOKEN=your_bot_token
    volumes:
      - ./bot.db:/app/bot.db
